name: enum_generator
description: This is a lightweight library to create functionality for enum class type and make enum usage much better.
version: 1.1.3
repository: https://github.com/cogivn/enum-generator
documentation: https://github.com/cogivn/enum-generator
issue_tracker: https://github.com/cogivn/enum-generator/issues
homepage: https://cogi.vn

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  analyzer: '>=7.0.0 <8.0.0'
  build: ^2.4.2
  build_config: ^1.1.2
  source_gen: ^2.0.0
  enum_annotation: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1